name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          APP_ENV: prod
        run: |
          ssh -i $SSH_PRIVATE_KEY user@your_server 'cd /path/to/project && git pull origin main && composer install --no-dev --optimize-autoloader && php bin/console doctrine:migrations:migrate && npm install && npm run build && sudo chown -R www-data:www-data var/cache var/log'


